Repository crystal-lang/crystal-website, pull requests merged in 2022-02, with the labels that each got.

#258 Reorganize css files
  _sass/_materialize.scss
  _sass/components/_footer.scss
  _sass/pages/_blog.scss
  _sass/pages/_community.scss
  _sass/pages/_conference.scss
  _sass/pages/_error.scss
  _sass/pages/_home.scss
  _sass/pages/_install.scss
  _sass/pages/_media.scss
  _sass/pages/_sponsors.scss
  _sass/pages/_team.scss
  _sass/pygment_black.scss
  _sass/stylesheet.scss
Labels: refactor

#265 Homogenizing the description used in feeds and the web page
  _config.yml
  _layouts/home.html
  index.html
Labels: refactor

#262 Remove `fullcalendar_overrides.scss`
  _sass/_fullcalendar_overrides.scss
Labels: refactor

#261 Fix `/style-guide` permalink
  style-guide.md
Labels: bug

#263 Add `raw_content` plugin for style-guide source
  _includes/blog_row.html
  _includes/style-guide/component.html
  _plugins/raw_content.rb
Labels: enhancement

#264 Split `_generic.scss` in typography and site styles
  _sass/_site.scss
  _sass/_typography.scss
  _sass/stylesheet.scss
Labels: refactor

#271 Fix team img preserve aspect ratio
  _sass/pages/_team.scss
Labels: bug
