Repository crystal-lang/crystal-website, pull requests merged in 2023-11, with the labels that each got.

#518 Allow resizing preview vierport in style guide
  _sass/pages/_styleguide.scss
Labels: enhancement

#517 Improvements in the merge algorithm of sponsors
  _data/opencollective.json
  _data/sponsors.csv
  assets/sponsors/kevin_hovsäter.jpg
  scripts/merge.cr
  scripts/opencollective.cr
  scripts/sponsors.cr
Labels: bug, topic:sponsors

#520 Update CrystalConf 2023 into retrospective + blog post
  _events/2023-crystal-berlin.html
  _posts/2023-11-09-memories-from-crystalconf.md
  assets/events/crystalconf2023/audience.jpg
  assets/events/crystalconf2023/cheers.jpg
  assets/events/crystalconf2023/christina.jpg
  assets/events/crystalconf2023/david.jpg
  assets/events/crystalconf2023/panel.jpg
  assets/events/crystalconf2023/tech.jpg
Labels: enhancement

#522 Add mixin `circle-image`
  _sass/components/_book-authors.scss
  _sass/elements/_avatar-list.scss
  _sass/main.scss
  _sass/mixins/_circle-image.scss
  _sass/pages/_sponsors.scss
Labels: enhancement

#523 Minor improvements to `book-author-icon`
  _includes/components/book-authors.html
  _sass/components/_book-authors.scss
Labels: enhancement

#524 Use `page_title` for book page
  _layouts/post.html
  _layouts/wide.html
  _pages/learning/crystal_programming.html
Labels: enhancement

#525 Fix `--white`
  _sass/_variables.scss
Labels: bug

#526 Left align `.content`
  _sass/components/_content.scss
Labels: bug

#528 Refine style
  _sass/_variables.scss
  _sass/base/_typography.scss
Labels: enhancement

#530 Add admin alumni
  _data/team.yaml
  _pages/team.html
Labels: enhancement

#531 Improve pagination style
  _sass/components/_post-navigation.scss
Labels: enhancement

#532 Add YouTube channel to community page
  _includes/icons/youtube.svg
  _pages/community.html
  _sass/components/_link-item.scss
Labels: enhancement

#527 Use manas SVG logo
  _data/others.json
  _data/sponsors.csv
Labels: enhancement

#535 Fix release date column to right align
  _pages/releases.html
  _sass/pages/_releases.scss
Labels: bug
