Repository crystal-lang/crystal-website, pull requests merged in 2023-05, with the labels that each got.

#442 Release post for 1.8.2
  _releases/2023-05-09-crystal-1.8.2-released.md
Labels: release

#445 Update on_opensuse.md 15.2 -> 15.4
  _pages/install/on_opensuse.md
Labels: enhancement

#448 Fix download.opensuse.org URLs with slashes in project path
  _includes/install/from_obs_deb.md
  _includes/install/from_obs_rpm.md
  install.sh
Labels: bug
