Repository crystal-lang/crystal-website, pull requests merged in 2023-03, with the labels that each got.

#409 Update font definitions
  _sass/_fonts.scss
  assets/fonts/roboto/Roboto-Bold.woff2
  assets/fonts/roboto/Roboto-Light.woff2
  assets/fonts/roboto/Roboto-Medium.woff2
  assets/fonts/roboto/Roboto-Regular.woff2
  assets/fonts/roboto/Roboto-Thin.woff2
  assets/fonts/roboto/roboto-mono-v22-latin-regular.woff2
  assets/fonts/roboto/roboto-v30-latin-100italic.woff2
  assets/fonts/roboto/roboto-v30-latin-300.woff2
  assets/fonts/roboto/roboto-v30-latin-300italic.woff2
  assets/fonts/roboto/roboto-v30-latin-500.woff2
  assets/fonts/roboto/roboto-v30-latin-500italic.woff2
  assets/fonts/roboto/roboto-v30-latin-700italic.woff2
  assets/fonts/roboto/roboto-v30-latin-italic.woff2
  assets/fonts/roboto/roboto-v30-latin-regular.woff2
Labels: enhancement

#411 Post: Breaking change PCRE2
  _posts/2023-03-02-crystal-is-upgrading-its-regex-engine.md
Labels: post

#424 Add verification backlink to fosstodon account
  index.html
Labels: enhancement

#425 Add page: releases
  _config.yml
  _includes/releases/links.html
  _layouts/release.html
  _pages/releases.html
  _sass/main.scss
  _sass/pages/_releases.scss
Labels: enhancement

#418 Add devenv with pre-commit configuration
  .envrc
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  Gemfile.lock
  README.md
  devenv.lock
  devenv.nix
  devenv.yaml
Labels: enhancement

#427 Blog fixes
  _sass/base/_typography.scss
  _sass/components/_post-teaser.scss
Labels: bug

#428 Add page: Sponsors
  .markdownlint.yaml
  _includes/pages/sponsors/table.html
  _includes/pages/sponsors/top_sponsors.html
  _includes/sponsors_sidebar.html
  _pages/sponsors.html
  _pages/sponsors.md
  _pages/style-guide.md
  _sass/base/_layout.scss
  _sass/base/_typography.scss
  _sass/components/_card.scss
  _sass/components/_cards-list.scss
  _sass/components/_side-section.scss
  _sass/components/_sponsor-card.scss
  _sass/elements/_hex.scss
  _sass/main.scss
  _sass/mixins/_blockflow.scss
  _sass/mixins/_box-link.scss
  _sass/pages/_sponsors.scss
  _sass/pages/_styleguide.scss
  _style_guide/components/card.html
  _style_guide/components/cards-list.html
  _style_guide/components/side-section.html
  _style_guide/elements/hex.md
Labels: enhancement

#431 Migrate to Google Analytics v4
  _includes/site/google_analytics.html
Labels: enhancement

#433 Add Mekhla to the team page
  _data/team.yaml
  assets/authors/RX14.jpg
  assets/authors/caspiano.jpg
  assets/authors/marksiemers.jpg
  assets/authors/mekhla.jpg
Labels: enhancement
