Repository crystal-lang/crystal-website, pull requests merged in 2024-03, with the labels that each got.

#676 Add component for partner images to illustrate partnerships
  _data/top_sponsors.csv
  _includes/components/partner-images.html
  _layouts/post.html
  _posts/2023-11-15-bright-manas-partnership.md
  _posts/2024-02-09-84codes-manas-mt.md
  _sass/components/_partner-images.scss
  _sass/components/_post-teaser.scss
  _sass/main.scss
  _style_guide/components/partner-images.html
  assets/blog/partners/manas+84codes.png
  assets/blog/partners/manas+bright.png
  assets/sponsors/84codes.svg
Labels: enhancement

#672 Improve HTML metadata and SEO
  _config.yml
  _data/authors.yaml
  _includes/components/testimonial-profile.html
  _includes/posts/meta.html
  _pages/releases/feed.xml
  feed.xml
  index.md
Labels: enhancement

#684 Add Crys to team page
  _pages/team.md
  assets/crys.svg
Labels: enhancement

#685 Fix typos
  _pages/install.md
  _pages/install/nightlies.md
  _pages/learning.md
Labels: bug

#686 Tune typography settings
  _sass/base/_typography.scss
  _sass/components/_sponsor-card.scss
  _sass/components/_topics.scss
  _sass/pages/_conference.scss
Labels: enhancement

#667 Refactor example tabs interaction
  _includes/pages/home/examples.html
  _sass/_utilities.scss
  _sass/components/_example-tabs.scss
  assets/js/_tabs.js
  assets/js/bundle.js
Labels: enhancement

#687 Improve frontmatter for latest posts
  _posts/2024-01-19-windows-support-1.11.md
  _posts/2024-02-09-84codes-manas-mt.md
  _posts/2024-02-28-the-return-of-the-golden-man.md
Labels: kind:chore

#689 Add default `height` and `width` to SVG icons
  _includes/icons/alternate-mail.svg
  _includes/icons/ameba.svg
  _includes/icons/apps.svg
  _includes/icons/book.svg
  _includes/icons/build.svg
  _includes/icons/check.svg
  _includes/icons/code.svg
  _includes/icons/crystal.svg
  _includes/icons/dev.to.svg
  _includes/icons/discord.svg
  _includes/icons/discourse.svg
  _includes/icons/download.svg
  _includes/icons/extensions.svg
  _includes/icons/folder.svg
  _includes/icons/font-download.svg
  _includes/icons/gitter.svg
  _includes/icons/label.svg
  _includes/icons/liberachat.svg
  _includes/icons/library-books.svg
  _includes/icons/manage-search.svg
  _includes/icons/mastodon.svg
  _includes/icons/matrix.svg
  _includes/icons/medium.svg
  _includes/icons/merge-type.svg
  _includes/icons/newsletter.svg
  _includes/icons/newsmode.svg
  _includes/icons/podcasts.svg
  _includes/icons/reddit.svg
  _includes/icons/rocket-launch.svg
  _includes/icons/rss-box.svg
  _includes/icons/rss.svg
  _includes/icons/schedule.svg
  _includes/icons/slideshow.svg
  _includes/icons/stack-overflow.svg
  _includes/icons/subscriptions.svg
  _includes/icons/telegram.svg
  _includes/icons/twitter.svg
  _includes/icons/update.svg
  _includes/icons/video-library.svg
  _includes/icons/video.svg
  _includes/icons/videocam.svg
  _includes/icons/youtube.svg
Labels: bug

#683 Improve and fix text on install pages
  _pages/install.md
  _pages/install/from_sources.md
  _pages/install/on_freebsd.md
  _pages/install/on_linux.md
  _pages/install/on_mac_os.md
  _pages/install/on_openbsd.md
Labels: enhancement

#682 Edit top-sponsors component
  _data/top_sponsors.csv
  _includes/components/top-sponsors.html
Labels: kind:chore

#690 Fix `box-link` to use `::before` pseudo element
  _sass/mixins/_box-link.scss
Labels: bug

#696 Polish *Success Stories* page
  _layouts/wide.html
  _pages/success-stories.md
Labels: bug, enhancement

#698 Capitalize category titles
  _data/nav.yml
  _includes/site/breadcrumbs.html
Labels: enhancement

#700 Update wording in sponspors FAQ
  _pages/sponsors.md
Labels: enhancement

#699 Fix `.icon` SVG width
  _sass/_utilities.scss
Labels: bug

#701 Make `thead` sticky
  _sass/elements/_table.scss
  _sass/pages/_sponsors.scss
Labels: enhancement

#706 Normalize `font-size` values
  _sass/_utilities.scss
  _sass/_variables.scss
  _sass/base/_typography.scss
  _sass/components/_card.scss
  _sass/components/_example-tabs.scss
  _sass/components/_footer.scss
  _sass/components/_navbar.scss
  _sass/components/_post-teaser.scss
  _sass/components/_profile-card.scss
  _sass/elements/_link-item.scss
  _sass/elements/_table.scss
  _sass/pages/_conference.scss
  _sass/pages/_install.scss
  _sass/utilities/_footnote.scss
Labels: refactor

#702 Remove duplicate sponsor card for Manas
  _includes/pages/sponsors/top_sponsors.html
Labels: enhancement

#707 Extract include `posts/more_articles.html`
  _includes/posts/more_articles.html
  _layouts/category.html
  _pages/blog.html
Labels: refactor

#705 Reword description of Crys on team page
  _pages/team.md
Labels: enhancement

#704 Avoid line break in section nav item
  _sass/components/_breadcrumbs.scss
Labels: enhancement

#708 Add taxonomy links
  _includes/posts/meta.html
  _includes/posts/more_articles.html
  _includes/posts/taxonomy.html
  _sass/_utilities.scss
  _sass/components/_post-teaser.scss
  _sass/pages/_blog.scss
Labels: enhancement

#697 Increase image size in .profile-mini
  _includes/components/top-sponsors.html
  _pages/team.md
  _sass/components/_profile-card.scss
  _sass/utilities/_text.scss
Labels: enhancement

#712 Fix hex button borders
  _sass/elements/_hex.scss
  _sass/pages/_home.scss
Labels: bug

#713 Improve dark mode
  _includes/media/color_sample.html
  _includes/media/gallery_item.html
  _sass/_utilities.scss
  _sass/_variables.scss
  _sass/base/_typography.scss
  _sass/components/_card.scss
  _sass/components/_footer.scss
  _sass/mixins/_link-with-icon.scss
  _sass/pages/_install.scss
Labels: enhancement

#716 Fix remove horizontal scroll bar
  _sass/_utilities.scss
  _sass/base/_layout.scss
  _sass/components/_footer.scss
  _sass/components/_navbar.scss
  _sass/pages/_conference.scss
  _sass/utilities/_full-width-rule.scss
Labels: bug

#715 Tag some posts
  _posts/2023-01-05-welcome-2023.md
  _posts/2023-02-07-introducing-mekhla.md
  _posts/2023-03-02-crystal-is-upgrading-its-regex-engine.md
  _posts/2023-03-06-reveal-type-in-crystal.md
  _posts/2023-03-23-llvm-opaque-pointers.md
  _posts/2023-05-15-update-in-steering-committee.md
  _posts/2023-07-06-windows-support-1.9.md
  _posts/2023-07-19-Remilia-interview.md
  _posts/2023-11-08-changes-in-the-teams.md
  _posts/2023-11-09-memories-from-crystalconf.md
  _posts/2023-11-15-bright-manas-partnership.md
  _posts/2024-01-19-windows-support-1.11.md
  _posts/2024-02-09-84codes-manas-mt.md
Labels: enhancement

#711 Add tags
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/posts/taxonomy.html
  _layouts/tag.html
Labels: enhancement

#721 Add missing `viewbox` attributes to ensure proper scaling
  _includes/icons/discord.svg
  _includes/icons/edit.svg
  _includes/icons/info.svg
  _includes/icons/matrix.svg
  _includes/icons/newsletter.svg
  _includes/icons/rss-box.svg
  _includes/icons/rss.svg
  _includes/icons/telegram.svg
  _includes/icons/twitter.svg
  _includes/icons/youtube.svg
Labels: bug

#722 Fix `line-height` in `.link-actions`
  _sass/components/_link-actions.scss
Labels: bug

#719 Increase contrast for headers in dark mode
  _sass/_variables.scss
  _sass/base/_typography.scss
Labels: enhancement

#726 Remove excess links from *Used in production*
  _data/companies.csv
Labels: kind:chore

#725 Reduce number of nav menu entries
  _data/nav.yml
Labels: enhancement

#724 Fine tune newsletter form
  _includes/site/newsletter-form.html
  _sass/components/_footer.scss
Labels: enhancement

#723 Fix layout on ultra small viewport widths
  _sass/base/_layout.scss
  _sass/components/_example-tabs.scss
  _sass/components/_featured-posts.scss
  _sass/components/_footer.scss
  _sass/components/_post-card.scss
  _sass/pages/_home.scss
Labels: bug

#727 Fix remove duplicate `repology` property
  _data/packages.yaml
Labels: bug

#728 Add reference to releases on *Install* page
  _pages/install.md
Labels: kind:chore

#720 Fix rendering issues in Safari on iOS
  _sass/_utilities.scss
  _sass/components/_callout.scss
  _sass/components/_copy-action.scss
  _sass/components/_link-actions.scss
  _sass/mixins/_link-with-icon.scss
Labels: bug

#730 Increase white space before manas logo in footer
  _includes/site/footer.html
  _sass/components/_footer.scss
Labels: kind:chore

#718 Add note about package source in Repology version info
  _data/packages.yaml
  _includes/elements/repology_badge.html
Labels: enhancement

#734 Extend white background to full gallery card
  _includes/media/gallery_item.html
  _sass/_utilities.scss
Labels: enhancement

#736 Sort sponsors by amount instead of level
  _data/sponsors.csv
  scripts/merge.cr
Labels: infra

#710 Increase other sponsor `all_time` by `last_payment` every month
  scripts/merge.cr
  scripts/sponsors.cr
Labels: infra/ci

#737 Add 84codes full contribution, including MT
  _data/others.json
  _data/sponsors.csv
Labels: topic:sponsors

#739 Add link icons to sponsor links in thank you callout
  _data/others.json
  _sass/components/_callout.scss
  _sass/mixins/_link-with-icon.scss
  assets/sponsors/nikola.svg
Labels: enhancement

#742 Remove excess template tag
  _data/packages-nightly.yaml
Labels: bug

#743 Add icons to blog category pills
  _includes/posts/taxonomy.html
  _includes/site/breadcrumbs.html
  _sass/components/_link-actions.scss
  _sass/components/_post-teaser.scss
  _sass/mixins/_link-with-icon.scss
Labels: enhancement

#745 Fix code samples
  _samples/4_syntax.md
  _samples/5_concurrency.md
Labels: bug

#748 Add default image for embedded web preview
  _config.yml
  _layouts/skeleton.html
  assets/banner.webp
Labels: enhancement

#744 New tiers post
  _posts/2024-03-25-new-sponsoring-tiers.md
  _sass/pages/_blog.scss
  assets/blog/2024/2024-03-26-open-collective-backers.webp
  assets/blog/2024/2024-03-26-open-collective-corporate.webp
  assets/blog/2024/2024-03-26-open-collective-donation.webp
  assets/blog/2024/2024-03-26-open-collective-sponsors.webp
Labels: post

#740 Refactor sponsor data and introduce small logo sponsors on homepage
  _data/others.json
  _data/sponsor_logos_l.csv
  _data/sponsor_logos_s.csv
  _data/top_sponsors.csv
  _includes/components/top-sponsors-icons.html
  _includes/pages/sponsors/sponsor-cards.html
  _pages/sponsors.md
  _sass/components/_top-sponsors.scss
  _sass/mixins/_link-with-icon.scss
  _style_guide/components/cards-list.html
  scripts/merge.cr
  scripts/sponsors.cr
Labels: enhancement

#749 Add crystal to devenv
  devenv.nix
Labels: infra

#750 Update sponsors with current legacy rules
  _data/sponsor_logos_s.csv
Labels: infra

#751 Remove Nikola logo and link from sponsors list
  _data/others.json
  _data/sponsors.csv
Labels: infra

#752 Fix page header layout
  _layouts/wide.html
  _sass/base/_layout.scss
Labels: bug

#755 Adjust links in blog post to new distinct pages
  _posts/2024-03-25-new-sponsoring-tiers.md
Labels: kind:chore

#754 Remove broken nightly download links for Windows
  _data/packages-nightly.yaml
Labels: bug

#756 Fix platform logos in dark mode
  _sass/mixins/_link-with-icon.scss
Labels: bug
