Repository crystal-lang/crystal-website, pull requests merged in 2024-02, with the labels that each got.

#595 Ensure `.centered` is actually centered in wide containers
  _sass/utilities/_text.scss
Labels: bug

#594 Refactor `.link-actions` implementation for improve reusability
  _sass/components/_link-actions.scss
  _sass/main.scss
  _sass/mixins/_link-with-icon.scss
Labels: refactor

#597 Fix unknown post author
  _includes/posts/meta.html
  feed.xml
Labels: enhancement

#599 Ignore github.com and twitter.com in link checker
  Makefile
Labels: infra

#601 Refactor `hex` to be more configurable
  _sass/elements/_hex.scss
Labels: refactor

#602 `devenv update`
  .pre-commit-config.yaml
  devenv.lock
Labels: infra

#603 Move scss functions to main layer
  _sass/components/_featured-posts.scss
  _sass/main.scss
Labels: refactor

#604 Refactor `link-with-icon` to use mask
  _sass/mixins/_link-with-icon.scss
Labels: refactor

#609 Enable pre-commit prettier to write
  .pre-commit-config.yaml
  devenv.nix
Labels: infra

#610 Refactor `releases.md`
  _includes/pages/releases/releases-table.html
  _pages/releases.md
Labels: refactor

#605 Add homepage
  _includes/pages/home/examples.html
  _includes/posts/recent_news.html
  _includes/site/footer.html
  _includes/site/nav.html
  _layouts/home.html
  _layouts/skeleton.html
  _pages/blog.html
  _sass/components/_example-tabs.scss
  _sass/components/_link-actions.scss
  _sass/components/_navbar.scss
  _sass/main.scss
  _sass/mixins/_blockflow.scss
  _sass/pages/_home.scss
  assets/home/pattern.svg
  index.html
  index.md
Labels: enhancement

#615 Remove layout `page-body`
  _layouts/page-body.html
  _pages/community/governance.md
Labels: kind:chore

#613 Fix broken hover effect on release links
  _includes/pages/releases/releases-table.html
  _sass/pages/_releases.scss
Labels: bug

#616 Format `blog_authors` as YAML
  _data/blog_authors.json
  _data/blog_authors.yaml
Labels: refactor

#617 Fix disable external link postfix on install page
  _sass/pages/_install.scss
Labels: bug

#619 Fix consistent main-width for all pages
  _sass/base/_layout.scss
Labels: bug

#618 Fix link style in example description
  _sass/base/_typography.scss
  _sass/components/_example-tabs.scss
Labels: bug

#612 Add header content to releases page
  _pages/releases.md
  _sass/components/_link-actions.scss
Labels: enhancement

#621 Improve callout syling
  _config.yml
  _includes/callout.html
  _sass/_variables.scss
  _sass/components/_callout.scss
  _style_guide/typography/callout-types.md
Labels: enhancement

#620 Improve colors for code highlighting
  _sass/_pygment_white.scss
  _sass/_variables.scss
  _sass/components/_highlight.scss
  _sass/main.scss
  _sass/pages/_home.scss
  _style_guide/typography/code-block.md
Labels: enhancement

#623 Refactor `callout` include
  _includes/callout.html
Labels: refactor

#625 Trim `<p>` from `markdownify` for inline elements
  _includes/pages/home/examples.html
  _includes/pages/install/archive-table.html
  _includes/pages/install/group.html
  _includes/site/page-header.html
  _layouts/event.html
  _pages/used_in_prod.md
Labels: bug

#626 Fix `link-with-icon-href` override by `<img>` tag
  _sass/mixins/_link-with-icon.scss
Labels: bug

#628 Strip HTML from title tag
  _layouts/skeleton.html
Labels: bug

#629 Remove unused files
  _includes/community_row.html
  _includes/newsletter-signup.html
  _includes/posts/blog_row.html
  _includes/site/conference_header.html
  _includes/site/header.html
  assets/js/_materialize.min.js
  assets/js/_pagination_in_place.js
Labels: kind:chore

#630 Ignore irrelevant files in git and Jekyll
  .gitignore
  _config.yml
Labels: kind:chore

#627 Improve page: Used in Production
  _includes/components/top-sponsors-icons.html
  _includes/components/top-sponsors.html
  _includes/icons/build.svg
  _includes/icons/domain.svg
  _includes/icons/laptop.svg
  _includes/icons/person.svg
  _includes/icons/science.svg
  _includes/icons/security.svg
  _includes/pages/used_in_prod/companies.html
  _pages/used_in_prod.md
  _sass/main.scss
  _sass/pages/_used-in-prod.scss
  assets/icons/forms_add_on.svg
Labels: enhancement

#631 Fix broken links
  _data/companies.csv
  _events/2021-crystal-1.0.md
  _pages/community.html
  _pages/install/from_snapcraft.md
  _pages/sponsors.md
  _pages/sponsors/original-sponsors.html
  _posts/2016-05-26-heroku-buildpack.md
  _posts/2016-12-29-crystal-new-year-resolutions-for-2017-1-0.md
  _posts/2017-12-19-this-is-not-a-new-years-resolution.md
  _posts/2018-01-08-top-5-reasons-for-ruby-ists-to-use-crystal.md
  _posts/2018-03-09-crystal-automated-release.md
  _posts/2019-09-06-parallelism-in-crystal.md
  _posts/2020-01-02-introducing-shardbox.md
  _posts/2020-08-24-announcing-new-apt-and-rpm-repositories.md
  _posts/2021-04-30-new-apt-and-rpm-repositories.md
  _posts/2022-06-13-latests-from-the-team.md
  _releases/2015-02-07-crystal-0.5.9-released.md
  _releases/2016-03-21-crystal-0.14.1-released.md
  _releases/2016-04-02-crystal-0.15.0-released.md
  _releases/2016-05-17-crystal-0.17.0-released.md
  _releases/2019-09-23-crystal-0.31.0-released.md
  _releases/2019-09-30-crystal-0.31.1-released.md
  _releases/2019-12-11-crystal-0.32.0-released.md
  _releases/2019-12-18-crystal-0.32.1-released.md
  _releases/2020-02-14-crystal-0.33.0-released.md
  _releases/2020-04-06-crystal-0.34.0-released.md
  _releases/2020-06-09-crystal-0.35.0-released.md
  _releases/2023-01-09-1.7.0-released.md
Labels: bug

#634 Improve accessibility
  _includes/components/top-sponsors.html
  _includes/elements/repology_badge.html
  _includes/icons/info.svg
  _includes/pages/install/archive-table.html
  _includes/pages/install/group.html
  _includes/pages/sponsors/table.html
  _includes/releases/links.html
  _includes/site/edit-on-github.html
  _includes/site/footer.html
  _includes/site/nav.html
  _includes/site/page-header.html
  _layouts/base.html
  _layouts/event.html
  _layouts/home.html
  _layouts/post.html
  _pages/community.html
  _pages/sponsors/original-sponsors.html
  _sass/utilities/_full-width-rule.scss
  _style_guide/components/link-actions.html
  index.md
Labels: enhancement

#635 Increase contrast for code highlighting
  _sass/_variables.scss
  _sass/pages/_home.scss
Labels: enhancement

#636 Improve HTML semantics
  _includes/icons/rss.svg
  _includes/site/footer.html
  _layouts/skeleton.html
  _pages/blog.html
  _pages/community.html
  _pages/install.md
  _pages/install/nightlies.md
  _pages/learning.md
  _pages/releases.md
  _pages/sitemap.html
  _sass/_utilities.scss
Labels: kind:chore

#639 Fix more broken links
  _posts/2020-08-24-announcing-new-apt-and-rpm-repositories.md
  _posts/2020-11-19-organising-raw-crystal.md
Labels: kind:chore

#638 Use webp exclusively for event images
  _pages/community.html
Labels: bug

#637 Styling for dead links
  _plugins/dead-links.rb
  _sass/_utilities.scss
Labels: enhancement

#640 Add `htmltest`
  .htmltest.yml
  _includes/pages/sponsors/table.html
  _pages/sponsors/original-sponsors.html
  _style_guide/components/link-actions.html
  _style_guide/components/link-item.html
  _style_guide/typography/footnotes.md
  devenv.nix
Labels: infra

#641 Fix broken links to github.com
  _pages/team.md
  _posts/2013-07-13-null-pointer-exception.md
  _posts/2013-09-04-happy-birthday-crystal.md
  _posts/2013-09-23-type-inference-part-1.md
  _posts/2016-12-26-insert-into-shard-values-crystal-db.md
  _releases/2016-05-05-crystal-0.16.0-released.md
Labels: bug

#644 Order sample file names by weight
  _includes/pages/home/examples.html
  _samples/1_server.md
  _samples/2_type_system.md
  _samples/3_null.md
  _samples/4_syntax.md
  _samples/5_concurrency.md
  _samples/6_bindings.md
  _samples/7_macros.md
  _samples/8_dependencies.md
Labels: refactor

#645 Apply `liquify` on page title
  _includes/site/page-header.html
  _layouts/wide.html
Labels: bug

#643 Add `THANKS` callout
  _config.yml
  _includes/callouts/thanks.html
  _pages/sponsors.md
  _releases/2014-06-19-crystal-0.1.0-released.md
  _releases/2014-12-04-crystal-0.5.4-released.md
  _releases/2015-06-23-crystal-0.7.4-released.md
  _releases/2016-05-05-crystal-0.16.0-released.md
  _releases/2016-05-17-crystal-0.17.0-released.md
  _releases/2016-06-14-crystal-0.18.0-released.md
  _releases/2016-11-22-crystal-0.20.0-released.md
  _releases/2018-06-15-crystal-0.25.0-released.md
  _releases/2018-06-28-crystal-0.25.1-released.md
  _releases/2018-08-09-crystal-0.26.0-released.md
  _releases/2018-08-27-crystal-0.26.1-released.md
  _releases/2018-11-01-crystal-0.27.0-released.md
  _releases/2019-01-30-crystal-0.27.1-released.md
  _releases/2019-04-17-crystal-0.28.0-released.md
  _releases/2019-06-05-crystal-0.29.0-released.md
  _releases/2019-08-01-crystal-0.30.0-released.md
  _releases/2019-09-23-crystal-0.31.0-released.md
  _releases/2019-09-30-crystal-0.31.1-released.md
  _releases/2019-12-11-crystal-0.32.0-released.md
  _releases/2019-12-18-crystal-0.32.1-released.md
  _releases/2020-02-14-crystal-0.33.0-released.md
  _releases/2020-04-06-crystal-0.34.0-released.md
  _releases/2020-06-09-crystal-0.35.0-released.md
  _releases/2020-06-19-crystal-0.35.1-released.md
  _releases/2021-01-26-crystal-0.36.0-released.md
  _releases/2021-02-02-crystal-0.36.1-released.md
  _releases/2021-03-22-crystal-1.0-what-to-expect.md
  _releases/2021-07-16-1.1.0-released.md
  _releases/2021-07-27-1.1.1-released.md
  _releases/2021-10-14-1.2.0-released.md
  _releases/2021-10-21-1.2.1-released.md
  _releases/2021-11-10-1.2.2-released.md
  _releases/2022-01-06-1.3.0-released.md
  _releases/2022-01-13-1.3.1-released.md
  _releases/2022-01-18-1.3.2-released.md
  _releases/2022-04-06-1.4.0-released.md
  _releases/2022-04-22-1.4.1-released.md
  _releases/2022-07-06-1.5.0-released.md
  _releases/2022-09-08-1.5.1-released.md
  _releases/2022-10-06-1.6.0-released.md
  _releases/2022-10-21-1.6.1-released.md
  _releases/2022-11-03-1.6.2-released.md
  _releases/2023-01-17-1.7.1-released.md
  _releases/2023-01-23-1.7.2-released.md
  _releases/2023-03-07-1.7.3-released.md
  _releases/2023-04-20-1.8.1-released.md
  _releases/2023-05-09-crystal-1.8.2-released.md
  _releases/2023-07-17-1.9.1-released.md
  _releases/2023-07-19-1.9.2-released.md
  _releases/2024-01-08-1.11.0-released.md
  _releases/2024-01-11-1.11.1-released.md
  _releases/2024-01-18-1.11.2-released.md
  _sass/components/_callout.scss
Labels: enhancement

#598 Use devenv in CI
  .github/workflows/ci.yml
  Makefile
Labels: infra/ci

#649 Tune text size for `link-item` description
  _sass/elements/_link-item.scss
Labels: kind:chore

#648 Refactor `copy-action` with mask image
  _sass/components/_copy-action.scss
  assets/js/copy-action.js
Labels: refactor

#647 Fix `event-card` img display after `<picture>` removal
  _sass/components/event-card.scss
Labels: bug

#651 Add page *Newsletter*
  _data/nav.yml
  _data/sections.yaml
  _includes/site/footer.html
  _includes/site/newsletter-form.html
  _pages/newsletter.html
  _pages/newsletter.md
  _sass/components/_footer.scss
  _sass/components/_link-actions.scss
Labels: enhancement

#652 Fix footer top margin
  _sass/base/_layout.scss
Labels: bug

#653 Fix `<ul>` height on used_in_prod
  _sass/pages/_used-in-prod.scss
Labels: bug

#654 Add used_in_prod to community nav
  _data/nav.yml
Labels: kind:chore

#655 Fix post subtitle tag
  _layouts/post.html
Labels: bug

#650 Improve examples
  _samples/1_server.md
  _samples/2_type_system.md
  _samples/3_null.md
  _samples/5_concurrency.md
  _samples/6_bindings.md
  _samples/8_dependencies.md
  _sass/components/_example-tabs.scss
Labels: enhancement

#656 Add page *Success Stories*
  _config.yml
  _data/blog_authors.yaml
  _data/nav.yml
  _includes/components/posts-list.html
  _includes/components/testimonial-profile.html
  _layouts/post.html
  _pages/success-stories.md
  _pages/used_in_prod.md
  _posts/success_stories/2019-05-01-using-crystal-to-power-the-iou-economy.md
  _posts/success_stories/2019-07-17-genome-analysis-powered-by-crystal.md
  _posts/success_stories/2020-02-11-nikola-motor-company.md
  _posts/success_stories/2023-01-24-placeos-environments.md
  _posts/success_stories/2024-02-02-crystal-the-lingua-franca.md
  _sass/components/_link-actions.scss
  _sass/components/_post-card.scss
  _sass/components/_post-teaser.scss
  _sass/components/testimonial-profile.scss
  _sass/main.scss
  _style_guide/components/post-card.html
  _style_guide/components/testimonial-profile.html
  assets/authors/alex-kampa.jpg
  assets/authors/elorest.jpg
  assets/authors/mpettinati.jpg
  assets/authors/peter-schols.jpg
  assets/blog/2019-05-01-sikoba.webp
  assets/blog/2019-07-17-diploid.webp
  assets/blog/2020-02-11-nikola-truck-front-panel.webp
  assets/blog/2020-02-11-nikola.webp
  index.md
Labels: enhancement

#660 Rename peter-schols to peterschols
  _data/blog_authors.yaml
  _posts/2017-10-27-diploid-and-crystal.md
  _posts/success_stories/2019-07-17-genome-analysis-powered-by-crystal.md
  _style_guide/components/testimonial-profile.html
  assets/authors/peterschols.jpg
Labels: refactor

#661 Dark mode
  _includes/icons/dev.to.svg
  _includes/icons/medium.svg
  _sass/_variables.scss
  _sass/base/_typography.scss
  _sass/components/_callout.scss
  _sass/components/_card.scss
  _sass/components/_cards-list.scss
  _sass/components/_copy-action.scss
  _sass/components/_footer.scss
  _sass/components/_top-sponsors.scss
  _sass/components/_topics.scss
  _sass/elements/_avatar-list.scss
  _sass/elements/_hex.scss
  _sass/mixins/_link-with-icon.scss
  _sass/pages/_conference.scss
  _sass/pages/_home.scss
Labels: enhancement

#664 Fix `post-pagination` link display
  _sass/components/_post-navigation.scss
Labels: bug

#658 Post: 84codes and Manas partner to iron multi-threading support
  _posts/2024-02-09-84codes-manas-mt.md
  assets/blog/2024-02-09-84code-manas.png
Labels: post

#668 Fix font size for list title in footer
  _sass/components/_footer.scss
Labels: bug

#614 Highlight minor releases
  _includes/pages/releases/releases-table.html
  _sass/pages/_releases.scss
Labels: enhancement

#646 Add link to release notes on blog index
  _pages/blog.html
  _sass/pages/_blog.scss
Labels: enhancement

#670 Limit max width of post-image
  _sass/components/_post-teaser.scss
Labels: enhancement

#671 Place comments in post article
  _layouts/post.html
  _sass/components/_post-teaser.scss
Labels: enhancement

#673 Remove Nikola from top-sponsors and improve Manas SVG
  _data/top_sponsors.csv
Labels: kind:chore
